/**
 * Provider Message Contract Verification – IntegrationEvent
 *
 * Verifies that event-publisher's processMessage() function produces
 * IntegrationEvent messages that conform to what siebel (and any
 * other subscriber) expects.
 *
 * Uses the actual processMessage code from event-publisher, exercised
 * against the consumer pact generated by siebel's message consumer test.
 *
 * ✅ Runs standalone — no Docker stack, Redis, or SQS needed.
 *    Only tests the message transformation logic.
 *
 * In a multi-repo setup:
 *   1. Siebel's message pact is fetched from the Pact Broker
 *   2. This test runs in the integration-layer CI pipeline
 *   3. It verifies event-publisher satisfies all message consumers
 */

import { MessageProviderPact } from "@pact-foundation/pact";
import path from "path";
import { describe, it } from "vitest";
import {
  processMessage,
  SqsMessageBody,
} from "../../lambda-event-publisher/src/app";

// ── Config ──────────────────────────────────────────────────────

const PACT_DIR = path.resolve(__dirname, "../../../pacts");

// ── Test data factories ─────────────────────────────────────────
// These simulate realistic SQS messages that soap-processor would produce.

function createServiceRequestMessage(): SqsMessageBody {
  return {
    requestId: "SBL-20260101120000",
    source: "soap-processor",
    timestamp: "2026-01-01T12:00:00.000Z",
    payload: {
      Action: "ServiceRequest",
      AccountId: "ACC-2048",
      ContactName: "John Doe",
      ServiceType: "Billing Inquiry",
      Priority: "NORMAL",
      Description: "Customer requesting invoice correction",
      Source: "Siebel CRM",
      RequestId: "SBL-20260101120000",
    },
  };
}

function createMinimalMessage(): SqsMessageBody {
  return {
    requestId: "MIN-20260101120000",
    source: "soap-processor",
    timestamp: "2026-01-01T12:00:00.000Z",
    payload: {},
  };
}

// ── Provider verification ───────────────────────────────────────

describe("Provider Verification: IntegrationEvent messages", () => {
  it("produces events conforming to siebel's expectations", async () => {
    const pact = new MessageProviderPact({
      messageProviders: {
        // Each key must match the 'expectsToReceive' string from the consumer test
        "an IntegrationEvent with status PROCESSED": () =>
          processMessage(createServiceRequestMessage()),

        "an IntegrationEvent with minimal payload": () =>
          processMessage(createMinimalMessage()),
      },
      pactUrls: [
        path.join(PACT_DIR, "siebel-integration-layer-events.json"),
      ],
      // State handlers for message-based interactions
      stateHandlers: {
        "default": async () => {
          // No state setup needed — processMessage is pure
        },
      },
    });

    await pact.verify();
  });
});
