include classpath("application.conf")

node-address {
  protocol = http
  host     = "0.0.0.0"
  port     = 9324
  context-path = ""
}

queues {
  integration-queue {
    defaultVisibilityTimeout = 10 seconds
    delay                    = 0 seconds
    receiveMessageWait       = 0 seconds
  }
}
