package com.integration.tests.contract.provider;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.*;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

/**
 * Provider Contract Verification – integration-layer SOAP API
 *
 * Verifies that the integration-layer (soap-processor behind API Gateway)
 * satisfies all consumer contracts from core-app-1 and siebel.
 *
 * ⚠️  Requires the Docker stack running:
 *     cd integration-layer && docker compose up -d
 *
 * Reads pact files from the target/pacts directory (generated by consumer tests).
 */
@Tag("contract")
@Provider("integration-layer")
@PactFolder("target/pacts")
@IgnoreNoPactsToVerify
@DisplayName("Provider Verification: integration-layer SOAP API")
class SoapApiProviderPactTest {

    private static final String PROVIDER_BASE_URL =
            System.getProperty("provider.base.url",
                    System.getenv().getOrDefault("PROVIDER_BASE_URL", "http://localhost:8080"));

    @BeforeAll
    static void waitForProvider() throws Exception {
        HttpClient client = HttpClient.newHttpClient();
        for (int i = 0; i < 10; i++) {
            try {
                HttpResponse<String> res = client.send(
                        HttpRequest.newBuilder()
                                .uri(URI.create(PROVIDER_BASE_URL + "/health"))
                                .GET().build(),
                        HttpResponse.BodyHandlers.ofString());
                if (res.statusCode() >= 200 && res.statusCode() < 300) return;
            } catch (Exception ignored) { }
            Thread.sleep(1000);
        }
        throw new RuntimeException(
                "Provider at " + PROVIDER_BASE_URL + " not healthy. " +
                "Make sure Docker stack is running: cd integration-layer && docker compose up -d");
    }

    @BeforeEach
    void setupTarget(PactVerificationContext context) throws MalformedURLException {
        if (context == null) return;
        URI uri = URI.create(PROVIDER_BASE_URL);
        context.setTarget(new HttpTestTarget(
                uri.getHost(),
                uri.getPort(),
                uri.getPath().isEmpty() ? "/" : uri.getPath()));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    @DisplayName("verifies pact interaction")
    void verifyPact(PactVerificationContext context) {
        if (context != null) context.verifyInteraction();
    }

    @State("the integration layer is available")
    void integrationLayerAvailable() {
        // Docker stack provides all infrastructure — no special setup needed
    }
}
